import type { AppProps } from "next/app";
import { useEffect, useState } from "react";
import { Provider } from "react-redux";
import Splash from "../src/components/Splash";
import { GlobalStyle, Layout } from "../src/components/Layout";
import { NavigationBar } from "../src/components/Navigator";
import Head from "next/head";
import { store } from "../src/store";

const MyApp = ({ Component, pageProps }: AppProps) => {
  const [mockDelay, setMockDelay] = useState(false);
  // const isLoadingComplete = useCachedResources();
  useEffect(() => {
    setTimeout(() => setMockDelay(true), 610);
  });

  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!mockDelay ? (
        <Splash />
      ) : (
        <>
          <GlobalStyle />
          <NavigationBar />
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </>
      )}
    </Provider>
  );
};

export default MyApp;
